language: generic 

sudo: required
services: 
  - docker

before_install:
  - docker build -t esaito01/docker-react -f Deckerfile.dev .

script:
###  - docker run -e CI=ture esaito01/docker-react npm run test -- --coverage
   - docker run -e CI=ture esaito01/docker-react npm run test