language: generic 

sudo: required
services: 
  - docker

before_install:
  - docker build -t esaito01/docker-react -f Dockerfile.dev .

script:
####  - docker run -e CI=ture esaito01/docker-react npm run test -- --coverage
   - docker run -e CI=ture esaito01/docker-react npm run test


deploy:
  provider: elasticeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-561130388491Info"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

  #http://dockerreact-env.eba-qvp7zypb.ap-northeast-1.elasticbeanstalk.com/

